---
server:
    port: 8888
spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/alexredmond/SpringCloudConfig
                    #username: u
                    #password: p
                    search-paths:
                       - 'ConfigurationFiles/**'
                       - 'ConfigurationFiles/application.properties'